### ISSUE TITLE
zander moment is not working because of an script error

### ISSUE THREAD

**Issue by ItzDonutScout** [Seamusmario/ZANDER-MOMENT#1]
ok look i tried to do this:
Your environment has been set up for using Node.js 12.18.3 (x64) and npm.

C:\Users\un>cd C:\Users\ZANDER-MOMENT

C:\Users\PC\ZANDER-MOMENT>npm install
npm WARN bonzibot@1.2.0 No repository field.

audited 31 packages in 2.044s
found 0 vulnerabilities

C:\Users\un\ZANDER-MOMENT>node index.js
initializing fuckervideo #0
initializing fuckervideo #1
posting fuckervideo
initializing fuckervideos #2
posting fuckervideo
initializing fuckervideos #3
posting fuckervideo
initializing fuckervideos #4
posting fuckervideo

but zander moment cannot appear in classic bonzi world. please fix this

**Comment by Seamusmario** [comment]
Classic bonzi.world does not work with bots.

**Comment by ItzDonutScout** [comment]
Oh i see.
